### ISSUE TITLE
Create empty migration template using migrate

### ISSUE THREAD

**Issue by madnesspie** [tortoise/aerich#101]
Hi! Thanks for new migrations format, `.sql` is really convenient. 

I have a little enhancement proposal. Sometimes a programmer needs to write migration manually. For example to define partial index or create a date migration. In this case a programmer should go to the REPL and generate the string then copy it and create a migration file. 

I guess a more convenient way is to use `--empty` console option for `aerich migrate` command how it works in [django](https://docs.djangoproject.com/en/3.1/topics/migrations/#data-migrations). If you agree I can contribute it.

**Comment by long2ice** [comment]
That's a good point. Of course PR is welcome.

**Comment by waketzheng** [comment]
`--empty` supported: https://github.com/tortoise/aerich/?tab=readme-ov-file#update-models-and-make-migrate
