### ISSUE TITLE
How to run aerich from python code?

### ISSUE THREAD

**Issue by evstratbg** [tortoise/aerich#104]
I want to make migrations before web app is up. Best way to make it?

**Comment by evstratbg** [comment]
any help?

**Comment by long2ice** [comment]
No plan to support this, or you can run system command in python code.

**Comment by metakot** [comment]
Seconding this.
A way to run migrations from python is a really good option to have.

**Comment by long2ice** [comment]
If  you want, you can use `os.system` to run aerich command

**Comment by long2ice** [comment]
Reopen this to look more.

**Comment by waketzheng** [comment]
Try this: https://github.com/tortoise/aerich/?tab=readme-ov-file#use-aerich-in-application
