### ISSUE TITLE
Aerich doesn`t work without aiomysql

### ISSUE THREAD

**Issue by klaipher** [tortoise/aerich#113]
[This import](https://github.com/tortoise/aerich/blob/dev/aerich/inspectdb.py#L6 ) triggers importing aiomysql client, though I don't use mysql
 Now aerich don`t work without installed aiomysql client, despite I use only postgres in my project.

**Comment by long2ice** [comment]
Your are right, fixed in dev branch. https://github.com/tortoise/aerich/commit/530e7cfce5e9857ecebbd397c02d2a058fd52fa6
