### ISSUE TITLE
backward relation "groups" duplicates in model User

### ISSUE THREAD

**Issue by Chise1** [tortoise/aerich#114]
If model_name is a variable ,got an error.
like this:
`
class Group(models.Model):
    label = fields.CharField(max_length=50)
    users = fields.ManyToManyField(settings.AUTH_USER_MODEL) 
    permissions = fields.ManyToManyField("models.Permission")

    def __str__(self):
        return self.label

`
error:
`  File "/home/chise/.cache/pypoetry/virtualenvs/fastapi-t-rYTP1qPO-py3.7/lib/python3.7/site-packages/tortoise/__init__.py", line 314, in _init_relations
    f'backward relation "{backward_relation_name}" duplicates in'
tortoise.exceptions.ConfigurationError: backward relation "groups" duplicates in model User
`

**Comment by FalseDev** [comment]
Your codeblocks are messed up, please fix them

**Comment by alexanderankin** [comment]
```python
class Group(models.Model):
    label = fields.CharField(max_length=50)
    users = fields.ManyToManyField(settings.AUTH_USER_MODEL)
    permissions = fields.ManyToManyField("models.Permission")

    def __str__(self):
        return self.label
```

```
error: File "/home/chise/.cache/pypoetry/virtualenvs/fastapi-t-rYTP1qPO-py3.7/lib/python3.7/site-packages/tortoise/init.py", line 314, in _init_relations
f'backward relation "{backward_relation_name}" duplicates in'
tortoise.exceptions.ConfigurationError: backward relation "groups" duplicates in model User
```
