### ISSUE TITLE
Aerich wants to alter instead of create new field.

### ISSUE THREAD

**Issue by DusanKovacevic94** [tortoise/aerich#116]
```
    exp = fields.FloatField(null=False, default=0)
    lvl = fields.IntField(null=False, default=0)
```
is updated to
```
    exp = fields.FloatField(null=False, default=0)
    lvl = fields.IntField(null=False, default=0)
    voice_exp = fields.FloatField(null=False, default=0)
    voice_lvl = fields.IntField(null=False, default=0)
```
Migrate creates this
```-- upgrade --
ALTER TABLE `users` RENAME COLUMN `exp` TO `voice_exp`;
ALTER TABLE `users` RENAME COLUMN `lvl` TO `voice_lvl`;
```

**Comment by long2ice** [comment]
So why not choice `False` when prompt `rename`?

**Comment by DusanKovacevic94** [comment]
Oh, I don't know why I thought this will delete `exp` and `lvl` to create `voice_exp` and `voice_lvl`.

**Comment by DusanKovacevic94** [comment]
`And if aerich guess you are renaming a column, it will ask Rename {old_column} to {new_column} [True], you can choice True to rename column without column drop, or choice False to drop column then create, note that the after maybe lose data.`
This part of the readme confused me.

**Comment by long2ice** [comment]
This can be optimizing
