### ISSUE TITLE
No changes detected

### ISSUE THREAD

**Issue by facundopadilla** [tortoise/aerich#119]
I am separating the models in different files, on the right you can see the script "settings.py" that allows me to load the modules where I have the models, when I do an "init-db" it works without problems, the other commands work but when I want to do the migrations, it says that it does not detect changes, I am seeing that some people are having the same problem, previously I got an error like this: "old_model does not have the method/attribute 'pop'", (I forgot to take the capture and did a "clear" unconsciously). 

I'm using FastAPI, Aerich, TortoiseORM and Dynaconf.

![image](https://user-images.githubusercontent.com/64610246/108135050-27332280-7096-11eb-9c10-d27395e15687.png)

**Comment by facundopadilla** [comment]
![image](https://user-images.githubusercontent.com/64610246/108144374-489d0a00-70a8-11eb-8fc3-8e027aba6b05.png)

**Comment by facundopadilla** [comment]
![image](https://user-images.githubusercontent.com/64610246/108144548-b47f7280-70a8-11eb-8506-421c369365a5.png)

**Comment by facundopadilla** [comment]
Before to execute: uvicorn main:application --reload

![image](https://user-images.githubusercontent.com/64610246/108148710-260eef00-70b0-11eb-92eb-6be3d8ac7234.png)

**Comment by long2ice** [comment]
What's the version?

**Comment by facundopadilla** [comment]
> Did you use latest version?

aerich==0.5.0
aiosqlite==0.16.1
asyncpg==0.21.0
click==7.1.2
ddlparse==1.9.0
dictdiffer==0.8.1
dnspython==2.1.0
dynaconf==3.1.2
email-validator==1.1.2
fastapi==0.63.0
h11==0.12.0
idna==3.1
iso8601==0.1.14
loguru==0.5.3
passlib==1.7.4
pydantic==1.7.3
pyparsing==2.4.7
PyPika==0.44.1
python-multipart==0.0.5
pytz==2020.5
six==1.15.0
starlette==0.13.6
tortoise-orm==0.16.21
typing-extensions==3.7.4.3
uvicorn==0.13.3

**Comment by long2ice** [comment]
If you upgrade with old version, you should clean `aerich` table in database, and remove `models` directory, then rerun `init-db`.

**Comment by facundopadilla** [comment]
> If you upgrade with old version, you should drop `aerich` table in database, and remove `models` directory, then rerun `init-db`.

I just did it and now I see this 

![image](https://user-images.githubusercontent.com/64610246/108151278-22319b80-70b5-11eb-98cb-9ae0a388b902.png)

**Comment by metakot** [comment]
I think aerich just dropped **PostgreSQL** support.
Whenever I change `CharField` to another length, the `migrate` command generates migration file with `CHANGE field field VARCHAR(256)` but the PostgreSQL needs `ALTER COLUMN field TYPE VARCHAR(256)`.
And if I change `null=False` to `null=True` it outputs `No changes detected`.

**Comment by long2ice** [comment]
Which is bug and will be fix later.

**Comment by long2ice** [comment]
Fixed in https://github.com/tortoise/aerich/commit/52151270e0491a8436461cdba94ff76678f0d986, just install from latest dev branch and try.

**Comment by vadim-shadrin** [comment]
I just figured out why we are getting a <No change detected> message. If we change the model before <aerich upgrade> receive such a message. To fix this, we need to move the changes to the stash, then <aerich upgrade> and then revert the changes from the stash and <aerich upgrade>. But I think this behavior is abnormal. Correct me if I'm wrong.

**Comment by vadim-shadrin** [comment]
I could suggest you fogot import  models  in __init__.py

**Comment by alexanderankin** [comment]
can we re-open this issue again? seems like a persistent one
