### ISSUE TITLE
Compatibility for apps with CLI 

### ISSUE THREAD

**Issue by Olegt0rr** [tortoise/aerich#123]
To read `POSTGRES_URI` my app uses CLI with `-c` flag (to provide config path)
How can I set up aerich to prevent CLI conflicts?

### Version
aerich==0.5.0
As described, I've dropped all database, removed migrations folder.

### Run command
```
aerich init-db
```

### Result
```
usage: aerich [-h] [-c C]
aerich: error: unrecognized arguments: init-db
```

#### aerich.ini
```ini
[aerich]
tortoise_orm = app.config.TORTOISE_ORM
location = ./migrations
```

#### app.config.TORTOISE_ORM
```python
TORTOISE_ORM = {
    "connections": {"default":POSTGRES_URI},
    "apps": {
        "models": {
            "models": ["app.models", "aerich.models"],
            "default_connection": "default",
        },
    },
}
```

**Comment by long2ice** [comment]
So strange

**Comment by Olegt0rr** [comment]
> So strange

It was affected by my app.
`app.config` imports cli to handle -c "config.yml" for my app.
So `cli` and `aerich` conflicts with each other.

It would be great if you know how to isolate aerich from app's cli

**Comment by Olegt0rr** [comment]
@long2ice is there any way to pass args for app module through aerich?
In my case: provide config path for app via -c

**Comment by long2ice** [comment]
Sorry I don't know what do mean

**Comment by Olegt0rr** [comment]
To run my app I use
```bash
python -m my_app -c config.yml
```
So, my app always waits for `-c config.yml`

When aerich trying to work with my app, it didn't pass `-c config.yml`, so my app can't get my config.

**Comment by long2ice** [comment]
What about split config file from you app?
