### ISSUE TITLE
Rename on field add

### ISSUE THREAD

**Issue by Olegt0rr** [tortoise/aerich#134]
On field add aerich asks to rename existing field (event it's not marked to delete)

### State 1
```python
class User(Model):
    first_name = CharField(max_length=255)
```

### State 2
```python
class User(Model):
    first_name = CharField(max_length=255)
    last_name = CharField(max_length=255)
```

### Run `aerich migrate`
`Rename first_name to last_name? [True]`

**Comment by long2ice** [comment]
Fixed, thanks to report!
