### ISSUE TITLE
Table rename: No changes detected

### ISSUE THREAD

**Issue by Olegt0rr** [tortoise/aerich#139]
#### 1. Create model User without setting custom table name.
```python
class User(Model):
    id = IntField(pk=True)
```

#### 2. Init db / create migrations. 
Table name is `user`

#### 3. Change table name for User model
```python
class User(Model):
    id = IntField(pk=True)

    class Meta:
        table = "users"
```

#### 4. Try to create migrations
`No changes detected`, but table name was changed!

**Comment by long2ice** [comment]
That should be fixed
