### ISSUE TITLE
aerich try to Rename field. I am just goint to add a new field

### ISSUE THREAD

**Issue by vadim-shadrin** [tortoise/aerich#145]
I have the model

```
class Image(TimestampedMixin, Model):
    id = fields.IntField(pk=True)
    width = fields.IntField()
    height = fields.IntField()
    file = fields.CharField(max_length=64, validators=[TextLengthValidator('file', 1, 255)])
```

But when I add  a new field  
test = fields.CharField(max_length=64)
Aerich ask  question:  Rename file to test? [True]:

Why?
How to add field in existing model?

**Comment by long2ice** [comment]
What's the version?

**Comment by vadim-shadrin** [comment]
aerich==0.5.0

**Comment by vadim-shadrin** [comment]
> What's the version?

aerich==0.5.0

**Comment by long2ice** [comment]
Try latest

**Comment by waketzheng** [comment]
If you don't want to rename, input `false` or `False` and press the `Enter`.
