### ISSUE TITLE
Problem with field extention

### ISSUE THREAD

**Issue by vadim-shadrin** [tortoise/aerich#146]
I  tried to extend field according to documentation. 
https://tortoise-orm.readthedocs.io/en/latest/fields.html#extending-a-field
But aerich.utils.get_tortoise_config() rised en exception. 
   Error: No config named "config.aerich"
I do not understand why? In other cases this method called and it does not rise an exception ?

**Comment by long2ice** [comment]
Could you show full code?

**Comment by vadim-shadrin** [comment]
> Could you show full code?

from tortoise import fields
from tortoise.models import Model

`from tortoise import fields
from tortoise.models import Model


class FileField(CharField):
    pass

class Image(TimestampedMixin, Model):
    """ Картинка. Дописать """
    id = fields.IntField(pk=True)
    width = fields.IntField()
    height = fields.IntField()
    file = fields.CharField(max_length=255, validators=[TextLengthValidator('file', 1, 255)])
    test = FileField(max_length=64)`

**Comment by vadim-shadrin** [comment]
```py
from tortoise.fields import CharField
from tortoise import fields
from tortoise.models import Model

class FileField(CharField):
    pass

class Image(TimestampedMixin, Model):
    id = fields.IntField(pk=True)
    width = fields.IntField()
    height = fields.IntField()
    file = fields.CharField(max_length=255)
    test = FileField(max_length=64)
```

**Comment by vadim-shadrin** [comment]
If clear database  and all migrations every thing is ok
