### ISSUE TITLE
Migration tries to set callable object repr as column default in SQL, fails

### ISSUE THREAD

**Issue by artem30801** [tortoise/aerich#147]
I made a custom object with __call__ method and pass it like:
```
role_number = NextNumber()

class Role(Model):
    id = fields.IntField(pk=True)
    number = fields.IntField(default=role_number)
```

When I called "aerich migrate" it gives following error:
AttributeError: 'NextNumber' object has no attribute '__name__'

When I impelemnt __name__ attribute for the object, it generates following SQL code in file in /migrate folder (among other lines)
ALTER TABLE `role` MODIFY COLUMN `number` INT NOT NULL  COMMENT 'Priority (ordering) of the role' DEFAULT '<function cogs.db_utils.NextNumber:<class \'cogs.roles.Role\'>:number>';
Obviously this leads to faililure of executing aerich upgrade command

**Comment by long2ice** [comment]
Yes, which should be ignore

**Comment by long2ice** [comment]
Fixed

**Comment by artem30801** [comment]
Thank you!
