### ISSUE TITLE
MySQL: Data too long for column 'content' at row 1" for aerich init-db and aerich upgrade

### ISSUE THREAD

**Issue by saintlyzero** [tortoise/aerich#154]
Aerich version - 0.5.3
Databae - MySQL 8
I have a total of 22 tables, and when I do `aerich init-db` I'm getting an error
> tortoise.exceptions.OperationalError: (1406, "Data too long for column 'content' at row 1")

The new `content` field to store the entire migration JSON in `Aerich` overflows the MySQL `text` dataype limit of [64 Kilobytes](https://stackoverflow.com/a/6766854/9848549)
```python
Aerich.create(
        version=version, 
        app=app, 
        content=get_models_describe(app),
 )
```
I manually changed the datatype of `content` to `JSON` in MySQL, and it worked

To make this the default behavior we'll have to update the Tortoise ORM `JSONField` which always stores it as a `Text` field for MySQL. I think this is because MySQL introduced `JSON` datatype from **MySQL 8.0**

@long2ice any workarounds to fix this?

**Comment by long2ice** [comment]
Latest dev branch use `JSON` already
