### ISSUE TITLE
aerich creates multiple sql queries for a single column update

### ISSUE THREAD

**Issue by FIRDOUS-BHAT** [tortoise/aerich#169]
Here is what I got,

`-- upgrade --
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE INT USING "subscription_duration"::INT;
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE INT USING "subscription_duration"::INT;
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE INT USING "subscription_duration"::INT;
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE INT USING "subscription_duration"::INT;
-- downgrade --
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE VARCHAR(100) USING "subscription_duration"::VARCHAR(100);
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE VARCHAR(100) USING "subscription_duration"::VARCHAR(100);
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE VARCHAR(100) USING "subscription_duration"::VARCHAR(100);
ALTER TABLE "studentchoices" ALTER COLUMN "subscription_duration" TYPE VARCHAR(100) USING "subscription_duration"::VARCHAR(100);
`

**Comment by long2ice** [comment]
Latest source fixed that

**Comment by FIRDOUS-BHAT** [comment]
great
