### ISSUE TITLE
数据库外键指定db_constraint=False   然后删除这个外键字段 迁移失败

### ISSUE THREAD

**Issue by jiyuzhi** [tortoise/aerich#179]
生成了两条sql 
ALTER TABLE `product` DROP FOREIGN KEY `fk_product_user_37721d57`;
ALTER TABLE `product` DROP COLUMN `user_id`;

执行 DROP FOREIGN KEY `fk_product_user_37721d57`; 会出错 因为指定了db_constraint=False  没有外键约束

**Comment by long2ice** [comment]
嗯，这里应该是一个bug，db_constraint=False不应该drop外键

**Comment by long2ice** [comment]
试试最新dev分支
