### ISSUE TITLE
ImportError: cannot import name 'Tortoise' from 'tortoise' (unknown location)

### ISSUE THREAD

**Issue by Mng-dev-ai** [tortoise/aerich#184]
After install aerich when I run aerich -h I got this error : 
ImportError: cannot import name 'Tortoise' from 'tortoise' (unknown location)

**Comment by spacemanspiff2007** [comment]
``pip install tortoise-orm``

**Comment by wwweww** [comment]
What version of python are you using? I had this problem when I was using 3.10. I solved it after dropping back to 3.9.

**Comment by andyfcx** [comment]
using 3.11, failed

**Comment by wwweww** [comment]
You can try returning your python version to 3.9 and try again because this module is incompatible with older versions of python

**Comment by andyfcx** [comment]
@wwweww Actually no, it's the problem of another package called tortoise, which is unrelated with this orm, just reinstall all tortoise-orm, everything works good.

**Comment by rajdeep1mg** [comment]
> @wwweww Actually no, it's the problem of another package called tortoise, which is unrelated with this orm, just reinstall all tortoise-orm, everything works good.

how to do that

**Comment by pawelkoston** [comment]
After accidental install of tortoise instead of tortoise-orm I had to manually remove it from virtual env.
```bash
pip3 uinstall tortoise #did not help
cd /path/to/env/lib/python3.11/site-packages/
rm -rf tortoise*
pip3 install tortoise-orm
```

**Comment by quvonchbek-dev** [comment]
@pawelkoston Worked, thank you.

**Comment by waketzheng** [comment]
If using poetry, this command may help:
```bash
poetry run pip install --force-reinstall --upgrade tortoise-orm
```
