### ISSUE TITLE
Error while importing configuration module: No module named 'app'

### ISSUE THREAD

**Issue by Reszkettle** [tortoise/aerich#188]
Following setup:
![obraz](https://user-images.githubusercontent.com/52221748/129255575-57153b47-70d0-457f-ba6a-1935882237c3.png)

![obraz](https://user-images.githubusercontent.com/52221748/129255673-26afb002-5f9a-4d0a-9b47-3ad5b0a6cd9f.png)

I'm prompt with the error in title whenever I want to run **aerich migrate**

**Comment by Reszkettle** [comment]
I believe that someone can help me with this matter... because it blocks my development so heavily :(

**Comment by long2ice** [comment]
You can rename change config to `config.TORTOISE_ORM` in `aerich.ini` depend on your dir struct

**Comment by Reszkettle** [comment]
@long2ice I've tried it this way but it still does not work, arent there any issues with how path is resolved underneath? im using win10 btw

**Comment by Reszkettle** [comment]
do you see any other possible problems?

**Comment by long2ice** [comment]
I'm not sure, you can try move `aerich.ini` and `migrations` in root dir then try

**Comment by Chenger1** [comment]
Have the same issue. Did you solve it?

**Comment by Reszkettle** [comment]
@Chenger1 not yet, still trying to find the cause

**Comment by Chenger1** [comment]
> @Chenger1 not yet, still trying to find the cause

What is you aerich version? 
I had 0.5.6 with this problem.
Try aerich version = 0.5.5.
I installed it a few minutes ago and commands work well. Maybe it is a bug in 0.5.6

**Comment by Reszkettle** [comment]
@Chenger1 I will test it as soon as I arrive home, i think that some PR with reverting those changes will be useful for future uses

**Comment by Jarvis1Tube** [comment]
I also tryied this on version 0.5.6 and had failure, no module named "app", 0.5.5 verision ok. Recomend to use 0.5.5 for a while.

**Comment by odi1n** [comment]
I decided to work with aerich, there was the same problem with applications, the version was 0.5.6, I killed a couple of hours to figure out what the problem was. I decided to go to the issue repository, and version 0.5.5 does not have such problems

**Comment by yhit** [comment]
https://github.com/tortoise/aerich/issues/189

**Comment by long2ice** [comment]
Fixed, try latest source code.

**Comment by Reszkettle** [comment]
@long2ice  I've tried to install aerich 0.5.7 but it says that there is no 0.5.7 version and the latest is 0.5.6

**Comment by Reszkettle** [comment]
@long2ice What I've also noticed is that previously switch back to **0.5.5** was working fine, but now 0.5.5 is not working anymore and it prompts me with me an error:
 
![obraz](https://user-images.githubusercontent.com/52221748/129614748-96b0bf22-a629-4895-99ea-0895585ed434.png)

**Comment by long2ice** [comment]
Just run `pip install git+https://github.com/tortoise/aerich.git@dev`, if no problem after try I will release it.

**Comment by long2ice** [comment]
released

**Comment by Reszkettle** [comment]
It does not work still, even in 0.5.7 version

**Comment by Reszkettle** [comment]
> 
> 
> @long2ice What I've also noticed is that previously switching back to **0.5.5** was working fine, but now 0.5.5 is not working anymore and it prompts me with me an error:
> 
> ![obraz](https://user-images.githubusercontent.com/52221748/129614748-96b0bf22-a629-4895-99ea-0895585ed434.png)

The same problem as above

**Comment by Reszkettle** [comment]
Okay i was stupid, I just forgot to unpack the list of models...
![obraz](https://user-images.githubusercontent.com/52221748/129799963-0ee0409b-fc98-410b-b8a1-8a6c8c01f18c.png)
