### ISSUE TITLE
Support pyproject.toml

### ISSUE THREAD

**Issue by ehdgua01** [tortoise/aerich#197]
Do you have a plan to support `pyproject.toml` for config?
Would I request PR If you don't have a plan?

**Comment by long2ice** [comment]
That's good, see https://github.com/tortoise/aerich/commit/24c1f4cb7d8c12f4dcccb104cca0694b54e928db

**Comment by ehdgua01** [comment]
@long2ice Hi,
First of all, thank you for your development. However, I think that should keep aerich.ini because that is useful when reducing config file(`pyproject.toml`) size and keep the backward compatibility.

Fyi,
I suggest [this library](https://github.com/hukkin/tomli) because that is faster than tomlkit(ref. https://github.com/hukkin/tomli#performance)

**Comment by onerandomusername** [comment]
Second the suggestion for tomli over tomlkit. 

Tomli is made for speed, tomlkit is a style preserving library. In my own experience, tomlkit takes around 12 seconds to parse a poetry.lock file, while tomli can parse poetry.lock in under a third of a second.

I've also never seen a library require tomlkit, either. Its always tomli or toml. However, toml is unmaintained, so the defacto standard has become tomli.

**Comment by waketzheng** [comment]
Done by #392
