### ISSUE TITLE
when aerich init-db: AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by wjhgg** [tortoise/aerich#220]
directory structure
![image](https://user-images.githubusercontent.com/52145145/146891149-fb199b83-2f27-48ce-972c-62d89f4d12cc.png)

in __init__.py
![image](https://user-images.githubusercontent.com/52145145/146892777-617d684b-6c76-427c-b923-7dca63ec1b79.png)

in db.py
![image](https://user-images.githubusercontent.com/52145145/146892807-b69e4877-9766-4f57-9ba2-2861f5e2b624.png)

in orm_init,py
![image](https://user-images.githubusercontent.com/52145145/146892861-0cf7e051-c6e7-4aa6-b08c-ace0e80dee74.png)

after i aerich init -t database.orm_init.TORTOISE_ORM
when i do aerich init-db, happend error:
`AttributeError: 'list' object has no attribute 'startswith'
`
I'm not sure if this structure is correct, but I think it can make the configuration very flexible

**Comment by long2ice** [comment]
`["aerich.models", *models]`

**Comment by wjhgg** [comment]
> 

this's right, but happend new question when aerich init-db: 
`tortoise.exceptions.OperationalError: (3144, "Cannot create a JSON value from a string with CHARACTER SET 'binary'.")`
I set charset is utf8mb4, for this, if i want to use optional parameters, how should me to set for db_url?

**Comment by wjhgg** [comment]
> > 
> 
> this's right, but happend new question when aerich init-db: `tortoise.exceptions.OperationalError: (3144, "Cannot create a JSON value from a string with CHARACTER SET 'binary'.")` I set charset is utf8mb4, for this, if i want to use optional parameters, how should me to set for db_url?

ohhhh, i found an amazing problem, when this question happending, the migration file was not created successfully, but the database table was created!
