### ISSUE TITLE
Custom index error.

### ISSUE THREAD

**Issue by StepanGavrilov** [tortoise/aerich#239]
I create custom index (inherit from Index). if I am not declare index_name in my Index, i have error:
`AttributeError: 'UniqueIndexWithCondition' object has no attribute 'index_name'`

if i declare a method index_name
```
def index_name(self, schema, model):
    pass
```
Creating a migrations with this at the beginning
```
-- upgrade --
DROP INDEX "None";
```
And have this error when trying to migrate
`tortoise.exceptions.OperationalError: index "None" does not exist`

**Comment by long2ice** [comment]
`index_name` should return the index name
