### ISSUE TITLE
fields.DecimalField can`t change max_digits, decimal_places by migrate

### ISSUE THREAD

**Issue by panla** [tortoise/aerich#246]
### env

- tortoise-orm==0.19.1
- asyncmy==0.2.5
- aerich==0.6.3

### desc

longitude = fields.DecimalField(max_digits=12, decimal_places=9)

if change it to

longitude = fields.DecimalField(max_digits=16, decimal_places=14)

aerich cant`t generate migrate file.

**Comment by Mukhametvaleev** [comment]
I have the same issue too :( Aerich shows "No changes detected"

**Comment by panla** [comment]
> 我也有同样的问题 :( Aerich 显示“没有检测到变化”

final, write a migration sql file to change it.
