### ISSUE TITLE
Problem mit default values from Enums

### ISSUE THREAD

**Issue by ninanomenon** [tortoise/aerich#250]
The mysql migration that aerich generates for enums has a problem with defaults 

This state here causes an error:
```sql
ALTER TABLE `station` ALTER COLUMN `connection` SET DEFAULT 'Connection.OFFLINE'
```

`pymysql.err.OperationalError: (1067, "Invalid default value for 'connection'")`

## The model on which this is based on:
```python
class Connection(Enum):
    ONLINE = "online"
    OFFLINE = "offline"

class Station(Base):
    ...
    connection: Connection = fields.CharEnumField(enum_type=Connection, default=Connection.OFFLINE)
    ...
```

After adjusting the alter table statement, upgrading the database to the latest migration works.

```sql
ALTER TABLE 'station' ALTER COLUMN 'connection' SET DEFAULT 'OFFLINE';
```

**Comment by long2ice** [comment]
What's the version? Seems not problem for that since of https://github.com/tortoise/aerich/blob/dev/aerich/ddl/__init__.py#L75

**Comment by ninanomenon** [comment]
Sorry for the long reply time, I was on holiday. In the project I have here, I use version 0.6.3

**Comment by waketzheng** [comment]
Use `class Connection(str, Enum)` instead, as the example in tortoise: https://tortoise.github.io/examples/basic.html#enumeration-fields

**Comment by waketzheng** [comment]
Close as Django get the same result.

**Comment by charleeBlaqTech** [comment]
> Use `class Connection(str, Enum)` instead, as the example in tortoise: https://tortoise.github.io/examples/basic.html#enumeration-fields

still themsame i got this "role" VARCHAR(15) NOT NULL  DEFAULT <function escape_str at 0x000001E0AE5323E0>, on the generated migration file and below is my model 

from enum import Enum
class RolesEnum(str, Enum):
    TENANT_ADMIN = "admin"
    HR_ADMIN = "HR admin"
    EMPLOYEE = "employee"



class BaseModel(Model):
    id = fields.CharField(max_length=40, pk=True, default=lambda: uuid7())
    role = fields.CharEnumField(RolesEnum, default=RolesEnum.TENANT_ADMIN)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)

    class Meta:
        abstract = True

**Comment by waketzheng** [comment]
@charleeBlaqTech Can't reproduce with aerich==0.8.1 and tortoise==0.24.0
I have this models:
```py
from enum import Enum
from tortoise import Model, fields, models

class RolesEnum(str, Enum):
    TENANT_ADMIN = "admin"
    HR_ADMIN = "HR admin"
    EMPLOYEE = "employee"

class BaseModel(Model):
    id = fields.CharField(max_length=40, pk=True, default=lambda: uuid7())
    role = fields.CharEnumField(RolesEnum, default=RolesEnum.TENANT_ADMIN)
    created_at = fields.DatetimeField(auto_now_add=True)
    updated_at = fields.DatetimeField(auto_now=True)

    class Meta:
        abstract = True

class Example(BaseModel):
    name = fields.CharField(max_length=64)
```
And got the following migration file by `aerich init-db`:
```py
from tortoise import BaseDBAsyncClient


async def upgrade(db: BaseDBAsyncClient) -> str:
    return """
        CREATE TABLE IF NOT EXISTS "example" (
    "id" VARCHAR(40) NOT NULL PRIMARY KEY,
    "role" VARCHAR(8) NOT NULL DEFAULT 'admin',
    "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "name" VARCHAR(64) NOT NULL
);
COMMENT ON COLUMN "example"."role" IS 'TENANT_ADMIN: admin\nHR_ADMIN: HR admin\nEMPLOYEE: employee';
CREATE TABLE IF NOT EXISTS "aerich" (
    "id" SERIAL NOT NULL PRIMARY KEY,
    "version" VARCHAR(255) NOT NULL,
    "app" VARCHAR(100) NOT NULL,
    "content" JSONB NOT NULL
);"""


async def downgrade(db: BaseDBAsyncClient) -> str:
    return """
        """
```
My db is postgresql and Python version is 3.11.9

**Comment by charleeBlaqTech** [comment]
> [@charleeBlaqTech](https://github.com/charleeBlaqTech) Can't reproduce with aerich==0.8.1 and tortoise==0.24.0 I have this models:
> 
> from enum import Enum
> from tortoise import Model, fields, models
> 
> class RolesEnum(str, Enum):
>     TENANT_ADMIN = "admin"
>     HR_ADMIN = "HR admin"
>     EMPLOYEE = "employee"
> 
> class BaseModel(Model):
>     id = fields.CharField(max_length=40, pk=True, default=lambda: uuid7())
>     role = fields.CharEnumField(RolesEnum, default=RolesEnum.TENANT_ADMIN)
>     created_at = fields.DatetimeField(auto_now_add=True)
>     updated_at = fields.DatetimeField(auto_now=True)
> 
>     class Meta:
>         abstract = True
> 
> class Example(BaseModel):
>     name = fields.CharField(max_length=64)
> And got the following migration file by `aerich init-db`:
> 
> from tortoise import BaseDBAsyncClient
> 
> 
> async def upgrade(db: BaseDBAsyncClient) -> str:
>     return """
>         CREATE TABLE IF NOT EXISTS "example" (
>     "id" VARCHAR(40) NOT NULL PRIMARY KEY,
>     "role" VARCHAR(8) NOT NULL DEFAULT 'admin',
>     "created_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
>     "updated_at" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
>     "name" VARCHAR(64) NOT NULL
> );
> COMMENT ON COLUMN "example"."role" IS 'TENANT_ADMIN: admin\nHR_ADMIN: HR admin\nEMPLOYEE: employee';
> CREATE TABLE IF NOT EXISTS "aerich" (
>     "id" SERIAL NOT NULL PRIMARY KEY,
>     "version" VARCHAR(255) NOT NULL,
>     "app" VARCHAR(100) NOT NULL,
>     "content" JSONB NOT NULL
> );"""
> 
> 
> async def downgrade(db: BaseDBAsyncClient) -> str:
>     return """
>         """
> My db is postgresql and Python version is 3.11.9

i will try to update the tortoise and aerich version to latest version and try again the. will revert thanks
