### ISSUE TITLE
`aerich upgrade` on empty does not work in 0.7.1 

### ISSUE THREAD

**Issue by jes5e** [tortoise/aerich#273]
With version 0.6.3 I am able to clone my project, create an empty db, and then run `poetry run aerich upgrade`, and all works like it should: the aerich table gets created along with all the tables for my models. 

After updating to version  0.7.1, when I run that command on an empty db, I get this message:  "No upgrade items found". 

Downgrading to 0.6.3 fixes the issue.

**Comment by exherb** [comment]
some issue here

**Comment by freakaton** [comment]
@jes5e that's because they moved from .sql migrations to .py and broke migrations, that was generated in `<0.7.0` ver. 

https://github.com/tortoise/aerich/blob/dev/CHANGELOG.md#070

**Comment by waketzheng** [comment]
No plan to compare v0.6
You can remove the migrations directory and then run `aerich init-db` to create tables in empty db.
