### ISSUE TITLE
Release fix for closing database connections on `aerich init-db`

### ISSUE THREAD

**Issue by nachomaiz** [tortoise/aerich#274]
Hi!

I saw that the #268 issue of not closing connections when using `aerich init-db` was fixed in PR #269 about 6 weeks ago, but has not been added to a release (v0.7.1 was released a couple of days before the fix was merged).

Would it be possible to push a bugfix release with this change? It is significantly affecting multi-connection sqlite setups, where one connection locks the process and blocks the following ones from being created (can't use Ctrl+C KeyboardInterrupt either).

I've made the fix manually on my local machine but it would have an impact on deployment.

In any case, great work on this project! Super fond of it and tortoise-orm! Thanks!

**Comment by baseplate-admin** [comment]
Hey any update on this?

Last release was on September ...

**Comment by nachomaiz** [comment]
I believe this issue got resolved when v0.7.2 was released on Jul 20.
