### ISSUE TITLE
Clarify aerich package versioning rules

### ISSUE THREAD

**Issue by leshark** [tortoise/aerich#289]
Hello, I have spotted that in version [v0.7.0](https://github.com/tortoise/aerich/releases/tag/v0.7.0) not backward compatible changes were made:
> Now aerich use .py file to record versions.

According to [semver](https://semver.org/) this should be a breaking change as generated sql file can be used somewhere else (changing them to `.py` files may break something + linters that lint `.sql` files will also break)

Not advocating for or against new functionality, however such a big change is usually not expected when updating a minor version.
Can you consider switching to `semver` or at least explicitly clarify versioning rules so more precise constraints can be used when updating `aerich`?

**Comment by Molkree** [comment]
> such a big change is usually not expected when updating a minor version

Because it's still v0.y.z it's in line with semver:

> Major version zero (0.y.z) is for initial development. Anything MAY change at any time. The public API SHOULD NOT be considered stable.

[link](https://semver.org/#spec-item-4)

Of course, it would be ideal if projects matured to v1 in 3 years and 37 releases :)

**Comment by leshark** [comment]
@Molkree let's use [ZeroVer](https://0ver.org/) then

**Comment by waketzheng** [comment]
@leshark @Molkree Thanks for your idea sharing. Aerich is used for tortoise-orm, so before the tortoise-v1.x.y released, the version of this lib will be always `0.x.y`
