### ISSUE TITLE
Aerich history don't working when update to version Aerich@0.7.1

### ISSUE THREAD

**Issue by hubertSotatek** [tortoise/aerich#293]
In version 0.6.3 of aerich package, when i run command `aerich history` after migrate database, it return list of migrated files 
```
0_20220519155613_init.sql
1_20220519155614_initdata.sql
2_20220526115614_addsearchbar.sql
3_20220719174014_addcategorymaptemplate.sql
4_20220727170350_update.sql
5_20220926114014_addyostorehometemplate.sql
6_20220926174000_createviewmoretextbutton.sql
7_20221027144000_createyomarttemplate.sql
8_20221104153100_createcategoryvariants.sql
8_20221107124000_variantcoff.sql
8_20221109131000_adddividerforcategoryvariantb.sql
9_20221123152500_setcategorymaptodefault.sql
10_20221202112200_createdefaulthometemplate.sql
11_20221205143000_createbrandnewvariants.sql
```
But in version 0.7.1 of aerich package, when run `aerich history`, it doesn't show up even though I migrated
```
No history, try migrate
```
Please help me with this issue

**Comment by long2ice** [comment]
Not recurrence
<img width="671" alt="image" src="https://user-images.githubusercontent.com/13377178/228196174-ef500b58-254d-4111-84b6-4a29b90a7a3d.png">

**Comment by hubertSotatek** [comment]
> Not recurrence <img alt="image" width="671" src="https://user-images.githubusercontent.com/13377178/228196174-ef500b58-254d-4111-84b6-4a29b90a7a3d.png">

Hmm your migration files is .py, but it can show history for .sql file i generated from `<0.7.0` ver. ?

**Comment by long2ice** [comment]
See 0.7.0 release note
