### ISSUE TITLE
aerich upgrade error with \windows_events.py", line 494, in finish_recv return ov.getresult() OSError: [WinError 64] 指定的网络名不再可用。

### ISSUE THREAD

**Issue by jiangying000** [tortoise/aerich#304]
I get this error when I run `aerich upgrade` `aerich history`  `aerich heads`

error msg in english is 'winError 64 the specified network name is no longer available'

**Comment by long2ice** [comment]
本机网络问题？

**Comment by jiangying000** [comment]
发现是没有建库，这个报错莫名其妙的

我也一直以为是什么网络问题

**Comment by jiangying000** [comment]
这种提示可以优化吗？

**Comment by waketzheng** [comment]
Mac系统报错是：
tortoise.exceptions.DBConnectionError: Can't establish connection to database aerich_dev2

Windows用的少，暂无优化计划。欢迎提PR。
