### ISSUE TITLE
在已有项目添加新的模型后 无法upgrade

### ISSUE THREAD

**Issue by kkv0id** [tortoise/aerich#305]
![image](https://github.com/tortoise/aerich/assets/31177595/43440a6e-9259-4403-a3cf-e740c6b793db)

数据库: MySQL
如上图，在生成的建表代码中 两个表之间 会有两个`;` 导致upgrade 无法执行，报错语法错误

**Comment by long2ice** [comment]
试试最新的源代码

**Comment by kkv0id** [comment]
暂时不方便使用 源代码测试；
目前使用的0.7.1 
生成代码看了下，一致的
@long2ice 

```
     content = MIGRATE_TEMPLATE.format(
            upgrade_sql=";\n        ".join(cls.upgrade_operators) + ";",
            downgrade_sql=";\n        ".join(cls.downgrade_operators) + ";",
        )
```

**Comment by kkv0id** [comment]
发现 159行  增加了 `operator = operator.rstrip(";") `
将其添加到使用的版本，测试了下没有出现两个`;`问题
