### ISSUE TITLE
varchar max_length change not detected

### ISSUE THREAD

**Issue by pawelkoston** [tortoise/aerich#317]
Example:
```python
field = fields.CharField(max_length=1, null=True, default=None,)
```
```bash
aerich init-db
```
Change length
```python
field = fields.CharField(max_length=2, null=True, default=None,)
```

```bash
aerich migrate; aerich upgrade;
```

The field length stays 1 but should be 2

**Comment by alexf-bond** [comment]
Did you try running aerich upgrade after the init-db to get the latest snapshot / version in the aerich table?  I know generally when making changes the flow is:
`aerich upgrade` -- get the current state of the migrations applied
`make necessary model changes`
`aerich migrate` -- detect and generate any new migrations
optionally `aerich upgrade` to apply any new migrations

**Comment by pawelkoston** [comment]
Thank you for help, that worked.
