### ISSUE TITLE
Has this repository been abandoned?

### ISSUE THREAD

**Issue by lozzo** [tortoise/aerich#356]
This repository hasn't been updated for a year. Has it been abandoned? This migration tool has many bugs, especially when it comes to foreign keys. It often fails and is completely unsuitable for production environments.

**Comment by pg** [comment]
@long2ice seems to be the only maintainer? There's been a number of semi-recent commits, but no new releases in over a year, which is odd considering the changes that have come in.

**Comment by henadzit** [comment]
@lozzo please feel free to open pull requests, I would gladly review them!

**Comment by grantmwilliams** [comment]
@henadzit, are you planning on generating a new release in the near future?

**Comment by henadzit** [comment]
@grantmwilliams, yes! I'll try to release the new version in the coming week.
