### ISSUE TITLE
aerich migrate --name add_index --empty does not works

### ISSUE THREAD

**Issue by kyle-li-dev** [tortoise/aerich#368]
Follow the README file, I ran this command but no files were generated.

And I got
```
Usage: aerich migrate [OPTIONS]
Try 'aerich migrate -h' for help.

Error: No such option: --empty Did you mean --help?

```

**Comment by waketzheng** [comment]
Before the next version release, you can use this command to fix it:
```bash
pip install git+https://github.com/tortoise/aerich
```

**Comment by kyle-li-dev** [comment]
Can I ask when the next version is expected to be released?

**Comment by waketzheng** [comment]
@abondar Shall we release a new version?

**Comment by abondar** [comment]
@waketzheng Yeah, sure

You can try to do it yourself, new version will be created on release creation in repository
