### ISSUE TITLE
两个问题，关于upgrade和downgrade

### ISSUE THREAD

**Issue by RunnerHong** [tortoise/aerich#38]
tortoise-orm==0.16.14 
aerich==0.2.2 

关于 upgrade:我这边修改字段，然后migrate、upgrade,没有效果。。
关于downgrade： tortoise.exceptions.IntegrityError: (1217, 'Cannot delete or update a parent row: a foreign key constraint fails')

**Comment by RunnerHong** [comment]
@long2ice 如果能把当前版本适配的tortoise-orm版本贴到readme中，那应该很好。我之前用的tortoise-orm==0.16.7, 没有Model.exists().所以就不行了。

**Comment by RunnerHong** [comment]
@long2ice 感谢

**Comment by long2ice** [comment]
可以查看生成的文件里面的SQL语句是否有问题
