### ISSUE TITLE
Tortoise Exception when excuting "aerich init-db"

### ISSUE THREAD

**Issue by ericzhang-debug** [tortoise/aerich#391]
Hello, my project uses FastAPI+Tortoise ORM+aerich and my file structure is: 
![image](https://github.com/user-attachments/assets/d01aa9c5-6c73-4129-82f4-52ef27742f49)

the red arrows point the model files that mappered to tables in database. The content of the model files like this:
![image](https://github.com/user-attachments/assets/bb3e4475-0ea3-4703-beec-99f16a80af87)
 
the file of ``` ./config/settings.py ```  is
```python
from tortoise import Tortoise
TORTOISE_ORM = {
    "connections": {
        "default": "sqlite://db.sqlite3",
        },
    "apps": {
        "models": {
            "models": [
                        "apps.historyDay.entities.historyDayCache",
                        "apps.oilPrice.entities.oilPriceCache"
                    ],
            "default_connection": "default",
        }
    }
}
```
When I excute ```aerich init-db```, it occured some errors:
![image](https://github.com/user-attachments/assets/333f2da0-bd2a-4900-af99-e7ec723a9543)

I have tried to add raw file with the name of ```__init__.py``` into the entities folders but it seemed no use.
What should I do to solve it?
Thank you very much

**Comment by waketzheng** [comment]
https://github.com/tortoise/aerich?tab=readme-ov-file#usage

<img width="648" alt="image" src="https://github.com/user-attachments/assets/b49cfe27-63cb-4092-81db-426a78838cb5" />

**Comment by ericzhang-debug** [comment]
Thank u very much
