### ISSUE TITLE
Process distributed models

### ISSUE THREAD

**Issue by mahenzon** [tortoise/aerich#41]
If models are distributed, for example this way:

```
├── models
│   ├── __init__.py
│   ├── user.py
│   ├── order.py
```

then you have to specify each file with model separately in the config array. It would be better if you could specify just the `models` module (all imports are in the `__init__.py`). But if I specify only the `models` module it imports this way:

```python
from models.user import User
from models.order import Order
```

and cannot process it properly, so creates a `CREATE TABLE` for each model when creating new migration again and again

___

also it needs to add a prepending new line in the `old_models` because it looks like this now:

```python
from tortoise import fields
from tortoise.models import Model


class User(Model):
    id = fields.IntField(pk=True)
    name = fields.TextField()
from tortoise import Model, fields

MAX_VERSION_LENGTH = 255


class Aerich(Model):
    version = fields.CharField(max_length=MAX_VERSION_LENGTH)
    app = fields.CharField(max_length=20)

    class Meta:
        ordering = ["-id"]
```

And if you forget to add an empty new line in the module, then line `from tortoise import Model, fields` joins the previous and breaks syntax

**Comment by waketzheng** [comment]
- Solution one -- explicit sub modules in config:
```py
DB_URL='postgres://postgres:postgres@127.0.0.1:5432/aerich_dev'
TORTOISE_ORM = {
    "connections": {"default": DB_URL},
    "apps": {"models": {"models": ["models.user", "models.order", "aerich.models"]}},
}
```
- Solution two -- auto load sub modules from models/:
```py
from pathlib import Path

def auto_load(strict=False) -> list[str]:
    models_dir = Path("models")
    files = [p for p in models_dir.glob("*.py") if p.name[0] != "_"]
    if strict:
        files = [p for p in files if b"fields." in p.read_bytes()]
    return [f"models.{p.stem}" for p in files]


TORTOISE_ORM = {
    "connections": {"default": DB_URL},
    "apps": {"models": {"models": [*auto_load(), "aerich.models"]}},
}
```
