### ISSUE TITLE
error: cannot import name '_wrap_std_stream' from 'asyncclick._winconsole' 

### ISSUE THREAD

**Issue by ShirleyChau** [tortoise/aerich#46]
My system is windows.
aerich version: dev.
When I try to use aerich init -h
and then I got the error:
`
(aerichtest-Io3kg-ro-py3.8) C:\Users\surface\PycharmProjects\aerichTest>aerich init -h
Traceback (most recent call last):
  File "C:\Users\surface\AppData\Local\pypoetry\Cache\virtualenvs\aerichtest-Io3kg-ro-
py3.8\Scripts\aerich-script.py", line 11, in <module>
    load_entry_point('aerich', 'console_scripts', 'aerich')()
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-
py3.8\lib\site-packages\pkg_resources\__init__.py", line 490, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-
py3.8\lib\site-packages\pkg_resources\__init__.py", line 2862, in load_entry_point
    return ep.load()
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-
py3.8\lib\site-packages\pkg_resources\__init__.py", line 2462, in load
    return self.resolve()
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-
py3.8\lib\site-packages\pkg_resources\__init__.py", line 2468, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-
py3.8\src\aerich\aerich\cli.py", line 8, in <module>
    import asyncclick as click
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-
py3.8\lib\site-packages\asyncclick\__init__.py", line 7, in <module>
    from .core import Argument
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-py3.8\lib\site-packages\asyncclick\core.py", line 18, in <module>
    from ._compat import isidentifier
  File "c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-py3.8\lib\site-packages\asyncclick\_compat.py", line 540, in <module>
    from ._winconsole import _get_windows_console_stream, _wrap_std_stream
ImportError: cannot import name '_wrap_std_stream' from 'asyncclick._winconsole' (c:\users\surface\appdata\local\pypoetry\cache\virtualenvs\aerichtest-io3kg-ro-py3.8\lib\site-packa
ges\asyncclick\_winconsole.py)
`

**Comment by long2ice** [comment]
Maybe there is compatibility trouble in windows with package `asyncclick`？

**Comment by ShirleyChau** [comment]
Maybe you need replace asyncclick to typer?

**Comment by long2ice** [comment]
It seems that typer don's support async?

**Comment by ShirleyChau** [comment]
If you need async,you can change close_dblike this:
`
def close_db(func):
    async def close_db_inner(*args, **kwargs):
        result = await func(*args, **kwargs)
        await Tortoise.close_connections()
        return result

    @functools.wraps(func)
    def close_db_inner2(*args, **kwargs):
        return asyncio.run(close_db_inner(*args, **kwargs))

    return close_db_inner2
`

**Comment by ShirleyChau** [comment]
def close_db(func):
    async def close_db_inner(*args, **kwargs):
        result = await func(*args, **kwargs)
        await Tortoise.close_connections()
        return result

    @functools.wraps(func)
    def close_db_inner2(*args, **kwargs):
        return asyncio.run(close_db_inner(*args, **kwargs))

    return close_db_inner2

**Comment by long2ice** [comment]
I remove `asyncclick` and you can try again.

**Comment by TrDex** [comment]
@long2ice Yes, that works. Thanks!

**Comment by TrDex** [comment]
@long2ice Please create a new release for this, otherwise Windows people will have that issue after updating `aerich`.

**Comment by JactyChan** [comment]
I have the same situation.
How to solve this problem.

**Comment by long2ice** [comment]
update to lastest dev branch
