### ISSUE TITLE
Sqlite3 upgrade problem

### ISSUE THREAD

**Issue by jottyVlad** [tortoise/aerich#47]
Migration was success, but I have exception when upgrade a DB.
![image](https://user-images.githubusercontent.com/44094832/93997704-5f129400-fd9c-11ea-8557-63c7e7086bb5.png)
![image](https://user-images.githubusercontent.com/44094832/93997804-75205480-fd9c-11ea-900f-00efada5f3b4.png)

**Comment by long2ice** [comment]
sqlite don't support modify syntax

**Comment by jottyVlad** [comment]
But I need to modify columns and this syntax was generated by aerich, is it not bug in aerich?...

**Comment by long2ice** [comment]
No, it's not a bug, sqlite itself don't support modify column, see https://www.sqlite.org/lang_altertable.html , and in latest dev branch I raise a `NotSupportError`.

**Comment by jottyVlad** [comment]
Thanks for your answer
