### ISSUE TITLE
mysql rename column?

### ISSUE THREAD

**Issue by ShirleyChau** [tortoise/aerich#53]
Rename mysql's column name is "ALTER TABLE `category` CHANGE `old_name` `name` VARCHAR(200) NOT NULL",not "ALTER TABLE `user` RENAME COLUMN `last_login` TO `last_login_at`"。

**Comment by long2ice** [comment]
You are partially right, mysql8.0+ support.

**Comment by ShirleyChau** [comment]
Maybe someone is using mysql 5.7.

**Comment by SakuraSound** [comment]
Want to reopen this. If someone is using mysql 5.7 the migration doesn't work. Would there be any proposal for enabling 5.7 support here?

**Comment by long2ice** [comment]
Now you can just choice no, which will delete old and create new field, next version will fix it.

**Comment by long2ice** [comment]
Added in dev branch

**Comment by SakuraSound** [comment]
Thanks for your response!
