### ISSUE TITLE
ERROR in version 0.2.4

### ISSUE THREAD

**Issue by AlexDemure** [tortoise/aerich#55]
_Pyenv with python 3.8.3_

`pip install aerich==0.2.4 `

 `aerich`

> Traceback (most recent call last):
>   File "/home/alex/.pyenv/versions/clever/bin/aerich", line 6, in <module>
>     from aerich.cli import main
>   File "/home/alex/.pyenv/versions/3.8.3/envs/clever/lib/python3.8/site-packages/aerich/cli.py", line 13, in <module>
>     from aerich.migrate import Migrate
>   File "/home/alex/.pyenv/versions/3.8.3/envs/clever/lib/python3.8/site-packages/aerich/migrate.py", line 8, in <module>
>     import click
> ModuleNotFoundError: No module named 'click'

_Pip freeze_
```
aerich==0.2.4
aiosqlite==0.15.0
anyio==2.0.2
asyncclick==7.1.2.1
idna==2.10
iso8601==0.1.13
pydantic==1.6.1
PyPika==0.41.0
sniffio==1.1.0
tortoise-orm==0.16.16
typing-extensions==3.7.4.3
```

**Comment by long2ice** [comment]
try latest dev branch.
