### ISSUE TITLE
Downgrade does not return old_models version 

### ISSUE THREAD

**Issue by falled10** [tortoise/aerich#57]
When i make downgrade it returns old version of database, but does not return old `old_models.py` version

**Comment by long2ice** [comment]
Yes, because don't record that.

**Comment by falled10** [comment]
@long2ice Is it planned in future? Because it makes no sense to make downgrade, as you cannot remove old migration and create new one

**Comment by long2ice** [comment]
Maybe should find a suitable way.

**Comment by long2ice** [comment]
This maybe resolved in 0.3.0.

**Comment by falled10** [comment]
@long2ice Thank you, but you have release issues, because v0.3.0 is latest and in v0.3.1 is fix for v0.3.0 but I cannot install v0.3.1 because last release is v0.3.0
