### ISSUE TITLE
how to  init a new database

### ISSUE THREAD

**Issue by panicneo** [tortoise/aerich#62]
使用版本：0.3.1
开发环境下初始化好migrations/models/xxx.json之后提交代码

目前尝试在一个新环境下（新数据库）初始化项目
1. 执行aerich upgrade会提示`relation "aerich" does not exist`
2. 执行aerich init-db会提示`Inited models already` 并且数据库中无任何变更

似乎是一个BUG？或者有无解决方案

**Comment by long2ice** [comment]
先执行`aerich init`再执行`aerich init-db`，或者删除`migrations/models`目录再执行`init-db`

**Comment by lucekdudek** [comment]
Hi, I have the same issue. I wish I am able to apply migrations generated in local environment and then apply them to new instance of DB server from migrations files. Right now `aerich init-db` make two things: 1) generates migrations files, 2) apply them to DB. In my opinion user of this repository should be able to generate migrations without DB and then applying migrations to DB in which `relation "aerich" does not exist`.

Quick fix for this would be to change `aerich upgrade` so it creates `relation "aerich"` if not exist but a more welcome change would be to allow migration generation without live DB.

**Comment by long2ice** [comment]
Fixed in https://github.com/tortoise/aerich/commit/6339dc86a8cdbe8311e3df9b279d95b14a91a3a4
