### ISSUE TITLE
init-db freezes

### ISSUE THREAD

**Issue by Andrexxelles** [tortoise/aerich#63]
![image](https://user-images.githubusercontent.com/52934588/96004234-d25f7100-0e43-11eb-864f-150a578909c6.png)

process freezes, if it hangs, it means something has broken and then it will not function normally, if the process is forcibly terminated, it says that old_models was not found, although it was created.

my test-project https://mega.dp.ua/ru/HYmMA9

**Comment by long2ice** [comment]
Don't use sqlite

**Comment by Andrexxelles** [comment]
I am using Postgresql how can this be specified? when connecting a db? 
NOT await Tortoise.init (db_url = 'sqlite: //database.db', modules = {'models': ['models']})
Right NOT await Tortoise.init (db_url = 'postgresqlite: //database.db', modules = {'models': ['models']}) ?

**Comment by long2ice** [comment]
Fixed in latest dev branch

**Comment by alanjds** [comment]
> Fixed in latest dev branch

Is back in `0.8.2` at least.

Could anyone please reopen?

**Comment by alanjds** [comment]
> > Fixed in latest dev branch
> 
> Is back in `0.8.2` at least.
> 
> Could anyone please reopen?

The regression was fixed on #435. Thanks @waketzheng

**Comment by budak7273** [comment]
In case it helps anyone else: A release with this fix isn't out yet as of writing. It can be built locally via `pip install "aerich @ git+https://github.com/tortoise/aerich"` (`aerich -V` reports `0.9.0`) as Alan mentioned [here](https://github.com/tortoise/aerich/issues/431#issuecomment-2704132697).
