### ISSUE TITLE
Config from callable?

### ISSUE THREAD

**Issue by TrDex** [tortoise/aerich#64]
# QUESTION
Is it possible to get config from callable function? As a workaround I change the source code in `utils.py:get_tortoise_config()` appending this check:
```python
if callable(config):
    return config()
return config
```

Is there any way to make it easier?

**Comment by long2ice** [comment]
Duplicated of  https://github.com/tortoise/aerich/issues/12

**Comment by TrDex** [comment]
Got it, thanks!
