### ISSUE TITLE
aerich migrate的时候出现编码错误

### ISSUE THREAD

**Issue by zhangyuxin123** [tortoise/aerich#65]
@long2ice @saintlyzero @psbleep 我在使用 aerich migrate的时候出现编码错误，如图所示，我该怎么解决？
![aerich migrate的时候出现编码错误](https://user-images.githubusercontent.com/23115864/96332394-4ee98e00-1096-11eb-9ccf-810dc8b800ec.png)

**Comment by saintlyzero** [comment]
You need to have the `description` value in utf-8

**Comment by zhangyuxin123** [comment]
> You need to have the `description` value in utf-8

At the beginning of py file, I have declared the utf8 encoding format, but it still can't work

**Comment by long2ice** [comment]
试试最新dev分支，应该已修复
