### ISSUE TITLE
Relative imports cause `aerich migrate` to fail

### ISSUE THREAD

**Issue by enchance** [tortoise/aerich#66]
I usually keep my pydantic models in a separate file from my db models but keep them both in the same folder. When it comes to importing these pydantic models, it fails terribly all because the location of the models has changed based on the *old_models.py* file. This causes `aerich migrate` to fail.

**app/ folder contains both files:**
```
# pydantic_models.py
class Pymodel(BaseModel):
    pass

# dbmodels.py
from .pydantic_models import Pymodel
class Dbmodel(models.Model):
    pass
```

This is where `aerich migrate` fails to migrate. To fix it, I need to use:

```
# Error
from .pydantic_models import Pymodel
# No error
from app.pydantic_models import Pymodel
```

It's a simple fix but I keep reminding myself to use the latter although I can see this being a problem to debug for new users if you don't understand the issue properly. I myself spent a lot of head scratching to find it out.

Before this I'd update *old_models.py* manually with the correct path but it seemed a bit too intrusive for me so I started using `from app.pydantic_models import Pymodel` instead.

**Comment by long2ice** [comment]
Yes now you can only use absolutely import.
