### ISSUE TITLE
Doesn't work for two DBs

### ISSUE THREAD

**Issue by GiteItAwayNow** [tortoise/aerich#68]
Hi there,

I'm building a service on FastAPI with Tortoise-ORM and I need to use two DBs for that.
The problem is that aerich doesn't work correctly in this situation.

I always get this warning from tortoise:
```
./offers_service/venv/lib/python3.8/site-packages/tortoise/__init__.py:556: RuntimeWarning: Module "aerich.models" has no models
  cls._init_apps(apps_config)
```

And I can't create correct migrations because aerich create it as there were not any migrations before - it creates db structure again.

My config:
```
TORTOISE_ORM = {
    'connections': {
        'read_connection': READ_DATABASE_URL,
        'write_connection': WRITE_DATABASE_URL
        },
    'apps': {
        'read_app': {
            'models': [
                'app.models.comments', 'app.models.post_likes',
                'app.models.posts', 'app.models.hashtags',
                'aerich.models'
                ],
            'default_connection': 'read_connection'
        },
        'write_app': {
            'models': [
                'app.models.comments', 'app.models.post_likes',
                'app.models.posts', 'app.models.hashtags',
                'aerich.models'
                ],
            'default_connection': 'write_connection'
        },
    },
}


def init_db(app: FastAPI) -> None:
    '''Initialize connection to the DB'''
    register_tortoise(
        app,
        config=TORTOISE_ORM,
        generate_schemas=False,
        add_exception_handlers=False,
    )


```

Also, it creates table "aerich" only for the first app .

**Comment by long2ice** [comment]
Fixed it, update from dev branch and try again.

**Comment by GiteItAwayNow** [comment]
Hi long2ice,

Thank you for the asnwer!

I've updated the package and my config - the warning is gone.

Unfortunately, I still can't create correct migrations.
I mean if I change something in my models and run `aerich --app read_app migrate --name change_column` - aerich create all migrations as if there were no migrations before. It describes all models again.

For example: if I change column name it doesn't create migration with ALTER TABLE - it creates CREATE TABLE IF NOT EXISTS with the renamed column.

My config:
```
TORTOISE_ORM = {
    'connections': {
        'read_connection': READ_DATABASE_URL,
        'write_connection': WRITE_DATABASE_URL
        },
    'apps': {
        'read_app': {
            'models': [
                'app.models.comments', 'app.models.post_likes',
                'app.models.posts', 'app.models.hashtags',
                'aerich.models'
                ],
            'default_connection': 'read_connection'
        },
        'write_app': {
            'models': [
                'app.models.comments', 'app.models.post_likes',
                'app.models.posts', 'app.models.hashtags'
                ],
            'default_connection': 'write_connection'
        },
    },
}
```

Steps which I done:

- aerich init -t app.db.TORTOISE_ORM
- aerich --app read_app init-db
- aerich --app read_app migrate

**Comment by long2ice** [comment]
Maybe aerich can't collect all models when init-db

**Comment by GiteItAwayNow** [comment]
Do you have any suggestion how to fix that?

**Comment by long2ice** [comment]
So why you add same models in different app? You only need different connection and use `using_db` when use

**Comment by long2ice** [comment]
update dev branch and try again, I updated it.

**Comment by GiteItAwayNow** [comment]
Hi long2ice,

Thank you! Updated but still no luck.

> So why you add same models in different app? You only need different connection and use using_db when use
I do it in this way because the file contains models for two apps, but it doesn't matter because it seems that the problem is in another thing.

It seems that the problem(migrations are incorrect) when I use custom app.

For example, migrations works good if my settings look like this:
```
TORTOISE_ORM = {
    'connections': {
        'default': READ_DATABASE_URL
        },
    'apps': {
        'models': {
            'models': ['app.models.read_models', 'aerich.models'],
            'default_connection': 'default'
        }
    },
}
```
But If I change it to:
```
TORTOISE_ORM = {
    'connections': {
        'default': READ_DATABASE_URL
        },
    'apps': {
        'read_app': {
            'models': ['app.models.read_models', 'aerich.models'],
            'default_connection': 'default'
        }
    },
}
```
and specify the app name in models meta
```
class UserModel(Model, ChangesTimeMixin):
    '''Base model to describe users table in DB'''
    id = UUIDField(pk=True, default=uuid.uuid4, unique=True, null=False)

    class Meta:
        app = 'read_app'
        table = 'users'
```
the migrations don't work correclty and aerich can't indicate changes - it create migrations with new tables but not changes.

**Comment by GiteItAwayNow** [comment]
Hi @long2ice,

I've chaned my code as you said(I use `using_db` now) and the migrations work.
But I think that there is still the bug with migrations. I'm not sure what the problem is.
Maybe because of I used abstract models.

Anyway, thanks for you help!
