### ISSUE TITLE
0.3.2 无法识别变更并且创建新的migration json

### ISSUE THREAD

**Issue by filwaline** [tortoise/aerich#70]
`aerich init -t app.db.base.TORTOISE_CONFIG`
> Success create migrate location ./migrations
   Success generate config file aerich.ini

```
# aerich.ini
[aerich]
tortoise_orm = app.db.base.TORTOISE_CONFIG
location = ./migrations
```

---

`aerich init-db`
> Success create app migrate location ./migrations/models
   Success generate schema for app "models"

生成了 `./migrations/models/9_20201030080750_None.json`

---

`aerich heads`
> No available heads,try migrate first

---

`aerich migrate`
> Success migrate 10_20201030080825_update.json

这里生成的json包含了upgrade和downgrade
- upgrade里面的SQL语句都是`CREATE TABLE IF NOT EXISTS ...`
- downgrade里面的SQL语句都是`DROP TABLE IF EXISTS ...`

这好像是又重复了`9_20201030080750_None.json`的内容，为什么会这样？
另外，downgrade好像很危险，如果执行了那么所有的表就都删除了？

---

修改models，增加了几个fields
...
`aerich migrate --name add_column`
> Success migrate 10_20201030080907_add_column.json

上一次migrate产生的 `10_20201030080825_update.json`被这次migrate产生的`10_20201030080907_add_column.json`给覆盖了，这里不是应该新增一个描述models变更的SQL语句的json吗？
`10_20201030080907_add_column.json`里面的内容也是`CREATE TABLE IF NOT EXISTS ...` 和 `DROP TABLE IF EXISTS ...`，根本无法完成数据库表结构的变更，为什么会这样？

**Comment by long2ice** [comment]
是初次使用还是从老版本升级？

**Comment by filwaline** [comment]
初次使用

---

在这之前models里面写了相对引入，导致无法正常使用，后来修改了models，使得aerich可以正常migrate
这可能是序号从8开始的原因？

**Comment by long2ice** [comment]
先把所有表删除，再删除migrations下models目录，从新从init-db开始操作

**Comment by filwaline** [comment]
> 先把所有表删除，再删除migrations下models目录，从新从init-db开始操作

不可以直接使用tortoise提供的`register_tortoise`和`init`是吗？

**Comment by long2ice** [comment]
也可以，但是init-db也要执行

**Comment by filwaline** [comment]
执行`aerich init-db`，产生了`./migrations/models/0_20201030084040_init.json`
执行`aerich migrate`, 产生了`1_20201030084130_update.json`
执行`aerich migrate --name add_col`, `1_20201030084208_add_col.json`覆盖了前面的`1_20201030084130_update.json`

这就跟之前报告的情况一样，只是文件名不同了

**Comment by long2ice** [comment]
这是正常情况，多次migrate但是不执行upgrade只会保留最新的一条

**Comment by filwaline** [comment]
> 这是正常情况，多次migrate但是不执行upgrade只会保留最新的一条

我去执行upgrade了，再次migrate确实得到了新增的json，但是内容依然是`CREATE TABLE IF NOT EXISTS ... `和 `DROP TABLE IF EXISTS ...`，这样还是不对，我期望看到的应该是 `ALTER TABLE ...`

**Comment by long2ice** [comment]
看看数据库里面aerich表有没有内容

**Comment by filwaline** [comment]
> 看看数据库里面aerich表有没有内容

有3行，分别对应目前的3个文件

**Comment by long2ice** [comment]
那不应该，看一下每个文件里面的内容

**Comment by filwaline** [comment]
./migrations/models/0_20201030090128_init.json
![image](https://user-images.githubusercontent.com/10396145/97688915-d3e09880-1ad5-11eb-81db-bcb0c0629a8b.png)

---

./migrations/models/1_20201030090140_update.json
![image](https://user-images.githubusercontent.com/10396145/97689030-f5418480-1ad5-11eb-8649-f8ddbdfd721a.png)

---

./migrations/models/2_20201030090241_add_col.json
![image](https://user-images.githubusercontent.com/10396145/97689100-0f7b6280-1ad6-11eb-9687-b98f375c3a40.png)

**Comment by filwaline** [comment]
> ./migrations/models/0_20201030090128_init.json
> ![image](https://user-images.githubusercontent.com/10396145/97688915-d3e09880-1ad5-11eb-81db-bcb0c0629a8b.png)
> 
> ./migrations/models/1_20201030090140_update.json
> ![image](https://user-images.githubusercontent.com/10396145/97689030-f5418480-1ad5-11eb-8649-f8ddbdfd721a.png)
> 
> ./migrations/models/2_20201030090241_add_col.json
> ![image](https://user-images.githubusercontent.com/10396145/97689100-0f7b6280-1ad6-11eb-9687-b98f375c3a40.png)

---

**Comment by filwaline** [comment]
![image](https://user-images.githubusercontent.com/10396145/97690170-97ae3780-1ad7-11eb-97c7-00a1059ce92f.png)

**Comment by long2ice** [comment]
不对啊，为什么没有其他model在里面

**Comment by filwaline** [comment]
其他的什么model？这里是我定义的全部model了

**Comment by filwaline** [comment]
我好像找到原因了，并且解决问题了，但是不确定这怎么导致了aerich无法正确工作。

---

我用了一个package来组织models，把各个model分别放到了不同的文件里，然后在同级的`__init__.py` 里面导入model，就像数据库的content列那样，只有一些导入语句。然后，我在TORTOISE_CONFIG里面models的路径是**直接**写了`"app.models"`, 而不是实际存放了model定义的文件路径，比如`"app.models.roles"`。
在将config中models的引用修改为类似`"app.models.*"`以后，ALTER语句就正确出现了。

**Comment by long2ice** [comment]
目前的机制是收集所有的model集中到一个文件中，然后新旧做对比，收集是到config的models配置对应的py文件里面进行copy

**Comment by filwaline** [comment]
> 目前的机制是收集所有的model集中到一个文件中，然后新旧做对比，收集是到config的models配置对应的py文件里面进行copy

那就建议你把这个明确写到文档中，migrate是怎么工作的
如果同样的配置能让tortoise正确工作，大概很少会有人怀疑配置写错了（事实上也没错，只是刚好跟aerich不对付

**Comment by long2ice** [comment]
针对你这种情况更新了一下，可以试试最新dev分支
