### ISSUE TITLE
数据迁移继承抽象类,无法迁移

### ISSUE THREAD

**Issue by lei7ma** [tortoise/aerich#71]
这是我的抽象类
![image](https://user-images.githubusercontent.com/45483884/97845014-f4ebf800-1d26-11eb-8ce9-915327186f51.png)
这个是我的配置
![image](https://user-images.githubusercontent.com/45483884/97845079-0f25d600-1d27-11eb-95e8-ee9e3cfd2079.png)
我的不同应用中model 继承抽象类就无法迁移,如果不继承就是可以的!
![image](https://user-images.githubusercontent.com/45483884/97845180-3b415700-1d27-11eb-9493-c67c8cbd9149.png)
![image](https://user-images.githubusercontent.com/45483884/97845234-501dea80-1d27-11eb-8db1-9072f5be6133.png)

**Comment by long2ice** [comment]
抽象类是支持的，不确定是哪里的问题

**Comment by lei7ma** [comment]
图片这边我看不到,不知道你能看到吗,
问题就是,我的抽象类封在一个utils/model.py 里,我的项目目录像django哪样,每一个应用下都会有一个models去继承这个抽象类,迁移就会报错 File "/home/malei/.virtualenvs/sanic/lib/python3.7/site-packages/tortoise/__init__.py", line 355, in _discover_models
    raise ConfigurationError(f'Module "{models_path}" not found')
tortoise.exceptions.ConfigurationError: Module "apps.users.models" not found
问题二: 只更新字段名,   aerich migrate  生成的语句是{
  "upgrade": [
    "ALTER TABLE `tb_user` RENAME COLUMN `email` TO `email2`"
  ],}

**Comment by long2ice** [comment]
你可以试试debug到对应的那一行看为什么报错，然后问题二有什么问题吗，rename字段是会有一个确认操作

**Comment by lei7ma** [comment]
ALTER TABLE `tb_user` RENAME COLUMN `email` TO `email2`;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN `email` TO `email2`' at line 1
是不是版本的问题啊

**Comment by long2ice** [comment]
是的，文档里写了，rename只支持MySQL8.0

**Comment by lei7ma** [comment]
好的谢谢
