### ISSUE TITLE
 Error: No config named "main"

### ISSUE THREAD

**Issue by lvar** [tortoise/aerich#74]
This is my file aerich.init

[aerich]
tortoise_orm = main.TORTOISE_ORM
location = .\migrations

I have the TORTOISE_ORM config on my main.py ...when I run aerich migrate...get this error:

Error: No config named "main"

Any idea ?

**Comment by long2ice** [comment]
What's your project struct?

**Comment by lvar** [comment]
Solved!!...the problem was different python version...but poetry doesn't show any error about it. Thanks anyway!

**Comment by lvar** [comment]
Having this same problem again...don't know why. I just upgrade some models and try to run aerich migrate... @long2ice

this is my project struct:

- app
    -routes
    -migrations
    -aerich.ini
    -main.py

Aerich.ini:

`  [aerich]
   tortoise_orm = main.TORTOISE_ORM
   location = .\migrations`
