### ISSUE TITLE
coding error

### ISSUE THREAD

**Issue by zhangyuxin123** [tortoise/aerich#75]
@long2ice hello, I have a coding error when using "aerich migrate", as shown in the figure, how can I solve it?
![96332394-4ee98e00-1096-11eb-9ccf-810dc8b800ec](https://user-images.githubusercontent.com/23115864/98466480-b49ae700-220a-11eb-8eab-5b40427a7ddb.png)

**Comment by long2ice** [comment]
Fixed it,update from latest dev branch and try again.
