### ISSUE TITLE
Custom migrations

### ISSUE THREAD

**Issue by KhDenys** [tortoise/aerich#76]
Hi @long2ice! 
Can I write my own migrations and how to do it? 
And can I create table records using migrations? 

Thank you very much.

**Comment by long2ice** [comment]
You can write custom sql in migration file after migrate

**Comment by KhDenys** [comment]
> You can write custom sql in migration file after migrate

@long2ice  Ok, but can I write sql queries to insert or delete rows in the migration file? And what is needed for this?

**Comment by long2ice** [comment]
No, just add it in `upgrade` section

**Comment by nejdetckenobi** [comment]
And can we do that without returning SQL queries like we do in Django? Is there an example for that?

**Comment by long2ice** [comment]
Now we use .py file to store version files, so you can write everything in it use Python.
