### ISSUE TITLE
Not able to proceed after init-db command !! 

### ISSUE THREAD

**Issue by ghost** [tortoise/aerich#78]
**aerich init-db**

`Success generate schema for app "models"`

_This has been done successfully ! Tables also created successfully_ 

After that I made few changes to the models and ran `aerich migrate --name init`

`tortoise.exceptions.ConfigurationError: No model with name 'Campaign' registered in app 'diff_models`

@long2ice please if you could help out here ! Thanks

**Comment by long2ice** [comment]
What's your models detail?

**Comment by omfd** [comment]
Hi @long2ice , Thanks for response. 

```
TORTOISE_ORM = {
    "connections": {"default": os.getenv("POSTGRES_URI")},
    "apps": {
        "models": {
            "models": models,
            "default_connection": "default",
        },
    },
}
```

**Comment by long2ice** [comment]
```py
TORTOISE_ORM = {
    "connections": {"default": os.getenv("POSTGRES_URI")},
    "apps": {
        "models": {
            "models": models,# What's it?
            "default_connection": "default",
        },
    },
}
```

**Comment by omfd** [comment]
Sorry @long2ice 


```
class BaseModel(Model):
    id = fields.UUIDField(pk=True)
    created_at = fields.DatetimeField(auto_now_add=True, index=True)
    created_by = fields.UUIDField(null=True)
    updated_at = fields.DatetimeField(auto_now=True, index=True)
```



```
class Campaign(BaseModel):
    name = fields.CharField(max_length=255, description='Campaign Name')
    target = fields.BigIntField(default=0)
    max_retries_per_user = fields.IntField(default=0)
    meta = fields.JSONField(default={
        "history": []
    })

    campaign_stages: fields.ReverseRelation
    users: fields.ReverseRelation
    users_definitions: fields.ReverseRelation

    event_group: fields.ForeignKeyNullableRelation = fields.ForeignKeyField(
        'models.EventGroup',
        null=True,
        on_delete=fields.SET_NULL
    )
    campaign_definition: fields.ForeignKeyNullableRelation = \
        fields.ForeignKeyField(
            'models.CampaignDefinition',
            related_name='campaigns',
            null=True,
            on_delete=fields.SET_NULL
        )

    class Meta:
        indexes = ('name')

    class PydanticMeta(BaseModel.PydanticMeta):
        exclude_raw_fields = False
        exclude = ("created_at", "updated_at")

```


tortoise.exceptions.ConfigurationError: No model with name 'Campaign' registered in app 'diff_models'.

**Comment by long2ice** [comment]
Maybe because 
```py
campaign_definition: fields.ForeignKeyNullableRelation = \
        fields.ForeignKeyField(
            'models.CampaignDefinition',
            related_name='campaigns',
            null=True,
            on_delete=fields.SET_NULL
        )
```
Keep it in one line since compatibility issue

**Comment by omfd** [comment]
Sure, @long2ice Thanks !! I am looking into it as well. I will report back the exact issue. The thing is `aerich init-db` worked without issue. `aerich migrate` failed !!

**Comment by ScrimForever** [comment]
@omfd . I have same problem when used ForeignKeyField.

aerich migrate same error

**Comment by sprnegr** [comment]
I have same problem with `aerich migrate`.

**Comment by Tears** [comment]
We can report the same problem. We were able to generate migration files for some models and upgrade them just fine, but after adding ForeignKeyFields and trying to migrate again, we are greeted with the following error:

`tortoise.exceptions.ConfigurationError: No model with name 'User' registered in app 'diff_models'.`

The ForeignKeyFields we added were very simple and do not reference User at all. One example of a field we added:

`menu_group = fields.ForeignKeyField('models.MenuGroup', on_delete='CASCADE', related_name="menu_items")`

**Comment by Tears** [comment]
It does seem to generate an old_models.py file for seemingly no reason. When and why is this file generated? This is the first time I'm seeing it, and like I said, we only added some ForeignKeyFields.

**Comment by Tears** [comment]
@long2ice Could you provide us with an update?

**Comment by Tears** [comment]
@long2ice We'd love to hear if you have the time to take a look to this issue, because at this time, it is halting development and we might have to look for something else.

**Comment by waketzheng** [comment]
https://github.com/tortoise/aerich/issues/107#issuecomment-2566170169
