### ISSUE TITLE
No line breaks in a migration file generated by init-db command

### ISSUE THREAD

**Issue by izdwuut** [tortoise/aerich#79]
Hi!

Due to migration files being saved in JSON format, the string containing a query to be performed can be full of `\n` characters. This is a limitation of JSON, as it doesn't allow multiline strings. But how about using YAML or some other format? I believe it would greatly increase readability of migration files.

Normally I try to be more detailed with these reports, but I'm just drained after 8 hours of work. If my description is too vague, I'd happily provide more details.

**Comment by long2ice** [comment]
Yes, json format has limitation, I will consider to replace it.
