### ISSUE TITLE
The program keeps stuck！

### ISSUE THREAD

**Issue by zhangyuxin123** [tortoise/aerich#90]
@long2ice After I use "aerich init-db", the program keeps stuck, as shown in the figure
![picture](https://user-images.githubusercontent.com/23115864/100361714-776d8c00-3035-11eb-8b29-c9466499b60d.jpg)

**Comment by long2ice** [comment]
Fixed

**Comment by goten002** [comment]
@long2ice I have the same issue with version 0.4.3, looks like the problem never fixed. The line "loop.run_until_complete(Tortoise.close_connections())" that fixes the problem is not there.

**Comment by artem30801** [comment]
Can confirm, all aerich commands make command line "stuck " with sqlite
