### ISSUE TITLE
AttributeError: type object 'Migrate' has no attribute 'dialect'

### ISSUE THREAD

**Issue by mariuscontoli** [tortoise/aerich#91]
Hi.
I have this message when I try to 'aerich upgrade'.
It seems to happen when I set the `"default": { "engine": "tortoise.backends.mysql",` tortoise configuration..

Any ideas ?

Thanks

![](https://files.slack.com/files-pri/TA75U55EV-F01FFSRL47Q/image.png)

**Comment by long2ice** [comment]
What's your db_url?

**Comment by long2ice** [comment]
That's a bug, fixed in v0.4.1

**Comment by mariuscontoli** [comment]
Thanks for the answer, I changed the way of proceeding.
