### ISSUE TITLE
 Aerich command error

### ISSUE THREAD

**Issue by zhangyuxin123** [tortoise/aerich#92]
@long2ice Hello，I found out that aerich's command was wrong
![Aerich command error](https://user-images.githubusercontent.com/23115864/100464515-b91b3700-3108-11eb-8d5f-d8149c96c261.png)

**Comment by long2ice** [comment]
What's the version?

**Comment by zhangyuxin123** [comment]
0.4.0

**Comment by lqmanh** [comment]
@long2ice I encountered this problem with v0.4.1. May you forget to add `packaging` to `pyproject.toml` or something?

**Comment by long2ice** [comment]
Fixed in [v0.4.2](https://github.com/tortoise/aerich/releases/tag/v0.4.2)
