### ISSUE TITLE
Aerich migrate -- name command error

### ISSUE THREAD

**Issue by zhangyuxin123** [tortoise/aerich#93]
@long2ice Aerich migrate -- name command error
![Aerich migrate -- name command error](https://user-images.githubusercontent.com/23115864/100492904-404dc680-316c-11eb-9ccc-fcc1c87c738a.png)

**Comment by long2ice** [comment]
check your config

**Comment by zhangyuxin123** [comment]
@long2ice This is my profile and directory structure
![This is my profile and directory structure](https://user-images.githubusercontent.com/23115864/100495407-7e57e400-3186-11eb-99e7-6e67b274e041.png)

**Comment by long2ice** [comment]
That's a bug, fixed in v0.4.1

**Comment by zhangyuxin123** [comment]
thanks，I'll try

**Comment by IgooorGP** [comment]
Thanks for the quick [c707f7e](https://github.com/tortoise/aerich/commit/c707f7ecb2eb2b1b383c7abda439ff89c87000ed) fix @long2ice , two days ago I had updated to the `0.4.0`version on a playground [project](https://github.com/IgooorGP/telegraph) of mine and started receiving the same error which forced me to fix the version on [0.3.3](https://github.com/IgooorGP/telegraph/blob/main/Pipfile#L21). Version `0.4.1` seems to have it fixed for me, now I can upgrade it on my project too.

Oh, and also thanks for the `json` change to `SQL` statements on [0.4.0](https://github.com/tortoise/aerich/releases/tag/v0.4.0), it has improved readability of the migrations a lot.
