### ISSUE TITLE
Version 0.4.1, stuck after using aerich init dB

### ISSUE THREAD

**Issue by zhangyuxin123** [tortoise/aerich#94]
@long2ice Version 0.4.1, stuck after using aerich init dB
![Version 0 4 1, stuck after using aerich init dB](https://user-images.githubusercontent.com/23115864/100495563-c62b3b00-3187-11eb-8e8a-4507151d96ae.png)

**Comment by long2ice** [comment]
That's sqlite bug, no solution to fix that now

**Comment by zhangyuxin123** [comment]
ok，thanks.
