### ISSUE TITLE
aerich init-db  Error: No config named "src.settings"

### ISSUE THREAD

**Issue by Chise1** [tortoise/aerich#95]
When I implemented  "aerich init-db",I got  an error:No config named "src.settings"
I'm sure my aerich.ini was true.

aerich.ini
[aerich]
tortoise_orm = src.settings.TORTOISE_ORM
location = ./migrations

.This is my folder tree:

├── aerich.ini
├── migrations
├── poetry.lock
├── pyproject.toml
├── src
│   ├── main.py
│   ├── models
│   │   └── __init__.py
│   └── settings.py
└── tests
    └── __init__.py

**Comment by Chise1** [comment]
In settings:
`
TORTOISE_ORM = {
    "connections": {
        "default": {
            "engine": "tortoise.backends.mysql",
            "credentials": {
                "host": DB_HOST,
                "port": DB_PORT,
                "user": DB_USER,
                "password": DB_PASSWORD,
                "database": DB_NAME,
                "echo": os.getenv("DB_ECHO") == "True",
                "maxsize": 10,
            },
        },
    },
    "apps": {
        "models": {
            "models": ["src.models", "aerich.models", ],
            "default_connection": "default",
        },
    },
}
`

**Comment by Chise1** [comment]
```
TORTOISE_ORM = {
    "connections": {
        "default": {
            "engine": "tortoise.backends.mysql",
            "credentials": {
                "host": DB_HOST,
                "port": DB_PORT,
                "user": DB_USER,
                "password": DB_PASSWORD,
                "database": DB_NAME,
                "echo": os.getenv("DB_ECHO") == "True",
                "maxsize": 10,
            },
        },
    },
    "apps": {
        "models": {
            "models": ["src.models", "aerich.models", ],
            "default_connection": "default",
        },
    },
}
```

**Comment by long2ice** [comment]
Did you run in project root dir?

**Comment by Chise1** [comment]
Yes.
My system is deepin v20. python version is 3.7 .
```
(fastapi-template-cu81P5JZ-py3.7) chise@chise-PC:~/PycharmProjects/fastapi_template$ aerich init-db
Usage: aerich [OPTIONS] COMMAND [ARGS]...
Try 'aerich -h' for help.

Error: No config named "src.settings"
(fastapi-template-cu81P5JZ-py3.7) chise@chise-PC:~/PycharmProjects/fastapi_template$ 

```

**Comment by long2ice** [comment]
That's confusing
